[package]
name = "aperture"
version = "0.1.0"
edition = "2018"

[dependencies]
aperture-common = { path = "../aperture-common" }
aperture-mesh = { path = "../aperture-mesh" }

ash = "0.32"
ash-window = "0.6"
cgmath = "0.18"
gpu-allocator = "0.8"
winit = "0.25"
